import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: "16px", md: "24px", lg: "40px" },
      screens: { sm: "640px", md: "768px", lg: "1024px", xl: "1280px" },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#8f4e00",
          foreground: "#ffffff",
          container: "#ff9933",
          "on-container": "#693800",
          fixed: "#ffdcc2",
          "fixed-dim": "#ffb77a",
          "on-fixed": "#2e1500",
          "on-fixed-variant": "#6d3a00",
        },
        secondary: {
          DEFAULT: "#435b9f",
          foreground: "#ffffff",
          container: "#9cb4fe",
          "on-container": "#2a4486",
          fixed: "#dbe1ff",
          "fixed-dim": "#b3c5ff",
          "on-fixed": "#00174a",
          "on-fixed-variant": "#2a4386",
        },
        tertiary: {
          DEFAULT: "#735c00",
          foreground: "#ffffff",
          container: "#d3ae36",
          "on-container": "#544200",
          fixed: "#ffe088",
          "fixed-dim": "#e9c349",
          "on-fixed": "#241a00",
          "on-fixed-variant": "#574500",
        },
        destructive: { DEFAULT: "#ba1a1a", foreground: "#ffffff" },
        success: { DEFAULT: "#50c878", foreground: "#ffffff" },
        surface: {
          DEFAULT: "#fcf9f8",
          dim: "#dcd9d9",
          bright: "#fcf9f8",
          "container-lowest": "#ffffff",
          "container-low": "#f6f3f2",
          container: "#f0eded",
          "container-high": "#eae7e7",
          "container-highest": "#e4e2e1",
        },
        outline: { DEFAULT: "#887364", variant: "#dbc2b0" },
        "background-cream": "#FFFEF2",
        "surface-white": "#ffffff",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#554336",
        "royal-ink": "#001B4D",
        "marigold-light": "#FFB84D",
        "emerald-growth": "#50C878",
      },
      fontFamily: {
        heading: ["var(--font-heading)", "Manrope", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "Be Vietnam Pro", "system-ui", "sans-serif"],
        marathi: ["var(--font-marathi)", "Noto Sans Devanagari", "sans-serif"],
        mukta: ["Mukta", "Noto Sans Devanagari", "sans-serif"],
        poppins: ["Poppins", "Noto Sans Devanagari", "sans-serif"],
        hind: ["Hind", "Noto Sans Devanagari", "sans-serif"],
        anek: ["Anek Devanagari", "Noto Sans Devanagari", "sans-serif"],
        noto: ["Noto Sans Devanagari", "sans-serif"],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
      },
      maxWidth: {
        container: "1280px",
      },
      boxShadow: {
        card: "0px 4px 20px rgba(143, 78, 0, 0.05)",
        elevated: "0px 8px 32px rgba(143, 78, 0, 0.08)",
        modal: "0px 16px 48px rgba(143, 78, 0, 0.12)",
      },
      backgroundImage: {
        "gradient-pink": "linear-gradient(135deg, #8f4e00 0%, #ff9933 50%, #d3ae36 100%)",
        "gradient-primary": "linear-gradient(135deg, #8f4e00 0%, #ff9933 50%, #d3ae36 100%)",
        "gradient-royal": "linear-gradient(135deg, #001B4D 0%, #435b9f 50%, #001B4D 100%)",
        "gradient-gold": "linear-gradient(135deg, #d3ae36 0%, #FFD700 50%, #d3ae36 100%)",
        "gradient-warm": "linear-gradient(135deg, #fcf9f8 0%, #ffdcc2 50%, #ffb77a 100%)",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-up": "slideUp 0.5s ease-out",
        "slide-down": "slideDown 0.3s ease-out",
        "slide-in-right": "slideInRight 0.25s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideInRight: {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}

export default config
